In [1]:
print("hello")

hello


In [3]:
import numpy as np
will= np.array([1,2,3,4,5])
print(will)
print(type(will))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
list1=[1,2,3,4]
arr1=np.array(list1)
print(arr1)

[1 2 3 4]


In [3]:
import numpy as np
list1=[1,2,3,4]
arr1=np.array(list1)
print(arr1.ndim)

1


In [4]:
import numpy as np
ar=np.array([1,2,3,4,5])
print(ar)


[1 2 3 4 5]


In [5]:
import numpy as np
ar=np.array([1,2,3,4,5])
print(ar)
ar[0]
ar[-1]
ar.ndim
ar.size

[1 2 3 4 5]


5

In [6]:
import numpy as np
ar=np.array([1,2,3,4,5])
print(ar)
ar[0]


[1 2 3 4 5]


1

In [7]:
import numpy as np
ar=np.array([1,2,3,4,5])
print(ar)
ar[-1]

[1 2 3 4 5]


5

In [8]:
import numpy as np
ar=np.array([1,2,3,4,5])
print(ar)
ar.ndim

[1 2 3 4 5]


1

In [1]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a

array([[1, 4],
       [5, 7],
       [3, 6],
       [3, 5]])

In [2]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a[0]

array([1, 4])

In [3]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a[1]

array([5, 7])

In [4]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a[2][0]

3

In [5]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a[2][1]

6

In [6]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.ndim

2

In [8]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.dtype

dtype('int32')

In [9]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.size


8

In [19]:
import numpy as np
b=np.array([[[1,4,8],[2,9,8]],[[6,7,8],[10,11,12]]],dtype=np.float64)
print(b)

[[[ 1.  4.  8.]
  [ 2.  9.  8.]]

 [[ 6.  7.  8.]
  [10. 11. 12.]]]


In [20]:
import numpy as np
b=np.array([[[1,4,8],[2,9,8]],[[6,7,8],[10,11,12]]],dtype=np.float64)
b[0][0][0]

1.0

In [21]:
import numpy as np
b=np.array([[[1,4,8],[2,9,8]],[[6,7,8],[10,11,12]]],dtype=np.float64)
b.ndim


3

In [23]:

import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
c=a.reshape(2,4)
print(c)

[[1 4 5 7]
 [3 6 3 5]]


In [24]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
c.ravel()


array([1, 4, 5, 7, 3, 6, 3, 5])

In [26]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.min()


1

In [27]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.max()

7

In [31]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
import numpy as np
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [38]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.sum(axis=0)

array([12, 22])

In [39]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
a.sum(axis=1)

array([ 5, 12,  9,  8])

In [40]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
np.sqrt(a)

array([[1.        , 2.        ],
       [2.23606798, 2.64575131],
       [1.73205081, 2.44948974],
       [1.73205081, 2.23606798]])

In [41]:
import numpy as np
a=np.array([[1,4],[5,7],[3,6],[3,5]])
np.mean(a)

4.25

In [43]:
x=np.array([[1,2],[2,3]])
y=np.array([[6,7],[4,5]])
z=x+y
print(z)

[[7 9]
 [6 8]]


In [44]:
x=np.array([[1,2],[2,3]])
y=np.array([[6,7],[4,5]])
z=x*y
z

array([[ 6, 14],
       [ 8, 15]])

In [45]:
x=np.array([[1,2],[2,3]])
y=np.array([[6,7],[4,5]])
x.dot(y)

array([[14, 17],
       [24, 29]])

In [49]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
2
3


In [47]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [48]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr1.dtype

dtype('int32')

In [4]:
import numpy as np
arr1=np.array([1.1,2.1,3.1,4.1,5.1])
arr1.dtype

dtype('float64')

In [5]:
import numpy as np
arr3=np.array(["A","B","C","D"])
arr3

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [6]:
import numpy as np
arr3.dtype

dtype('<U1')

In [8]:
import numpy as np
arr4=np.array([1,2,3,4,5],dtype=np.int64)
arr4

array([1, 2, 3, 4, 5], dtype=int64)

In [10]:
arr7=np.array([1,2,3,4,5],dtype=np.int8)
arr7

array([1, 2, 3, 4, 5], dtype=int8)

In [9]:
import numpy as np
arr6=np.array([1,2,3],dtype='i2')
arr6.dtype

dtype('int16')

In [11]:
arr8=arr7.astype(np.float16)
arr8

array([1., 2., 3., 4., 5.], dtype=float16)

In [13]:
arr9=arr7.astype(np.uint16)
arr9

array([1, 2, 3, 4, 5], dtype=uint16)

In [17]:
import numpy as np

list1=[1,2,3,4]
arr1=np.array(list1)
arr1

array([1, 2, 3, 4])

In [19]:
import numpy as np
tuple1=(10,20,30)
arr12=np.array(tuple1)
arr12

array([10, 20, 30])

In [20]:
arr20=np.zeros(5)
arr20

array([0., 0., 0., 0., 0.])

In [21]:
arr21=np.zeros([1,2])
arr21

array([[0., 0.]])

In [23]:
arr22=np.zeros([3,2,4])
arr22

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
import numpy as np
arr23=np.ones([7,10])
arr23

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
import numpy as np
l=[1,2,3,4,5]
arr24=np.array([l])
arr24=l[3]+l[3]
arr24


8

In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [7]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5],[4,5,6]])
(arr[1:])

array([[3, 4, 5],
       [4, 5, 6]])

In [12]:
import numpy as np
arr = np.array([0,1, 2, 3, 4, 5, 6, 7,8,9,10,11,12])
(arr[::2])

array([ 0,  2,  4,  6,  8, 10, 12])

In [14]:
import numpy as np
arr = np.array([0,1, 2, 3, 4, 5, 6, 7,8,9,10])
(arr[1:7])

array([1, 2, 3, 4, 5, 6])

In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr[2,1])
print(arr[3,1])
print(arr[3,2])

8
11
12


In [25]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[0,1,0])


3


In [26]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[1,1,0])

7


In [30]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
(arr[1,1,0:2])

array([10, 11])

In [32]:
import numpy as np
x=np.array([[5,6,7],[8,9,10]])
y=np.array([1,2,3])
z=x-y
z

array([[4, 4, 4],
       [7, 7, 7]])

In [34]:
import numpy as np
array=np.array([1,5,8,12,20,3])
v=array>10
filtered_array=array[v]
print("orginal array",array)
print("Filtered Array (elements > 10):", filtered_array)

orginal array [ 1  5  8 12 20  3]
Filtered Array (elements > 10): [12 20]


In [39]:
import numpy as np
array=np.array([1,5,8,12,20,3])
x=(array>5)&(array<15)
y=array[x]
print("orginal array",array)
print(y)

orginal array [ 1  5  8 12 20  3]
[ 8 12]


In [40]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [41]:
import numpy as np

arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [1]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = arr[[True, False, True, False]]
print(x)


[41 43]


In [2]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr] 

print(filter_arr)
print(newarr)



[False, False, True, True]
[43 44]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr=[]
for element in arr:
    if element % 2 == 0:
       filter_arr.append(True)
    else:
       filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [10]:
import numpy as np
arr = np.array([4, 2, 4, 84])
filter_arr = arr < 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[ True  True  True False]
[4 2 4]


In [11]:
import numpy as np
arr=np.array([8,9,6,7])
print(np.sort(arr))

[6 7 8 9]


In [16]:
import numpy as np
identify_matrix=np.eye(3)
print(identify_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
import numpy as np
identify_matrix=np.eye(3,4, dtype=int)
print(identify_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [19]:
import numpy as np
rectangular_matrix=np.eye(3,5)
print(rectangular_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [20]:
import numpy as np
matrix=np.eye(4,k=1)
print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [27]:
import numpy as np
arr=np.empty((2,5))
print(arr)

[[nan  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [24]:
import numpy as np 
arr=np.full((2,3),7)
print (arr)

[[7 7 7]
 [7 7 7]]


In [28]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [31]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(arr[0])
print(arr[1,1])
print(arr[1,2,3])
print(arr[:,0,:])
print(arr[0,:,1:3])
print(arr[1,1:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[17 18 19 20]
24
[[ 1  2  3  4]
 [13 14 15 16]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[19 20]
 [23 24]]


In [33]:
import numpy as np
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
z=x+y
z

array([[13, 12],
       [10, 15]])

In [34]:
import numpy as np
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
z=x*y
z

array([[40, 36],
       [16, 54]])

In [36]:
import numpy as np
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
z=x.dot(y)
z

array([[ 52,  66],
       [ 82, 102]])

In [37]:
import numpy as np
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
z=x/y
z

array([[0.625, 1.   ],
       [4.   , 1.5  ]])

In [38]:
import numpy as np
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
z=x-y
z

array([[-3,  0],
       [ 6,  3]])

In [42]:
import numpy 
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
print (numpy.add(x,y)) 
print(numpy.subtract(x,y))
print(numpy.divide(x,y))
print(numpy.multiply(x,y))
print(numpy.dot(x,y))

[[13 12]
 [10 15]]
[[-3  0]
 [ 6  3]]
[[0.625 1.   ]
 [4.    1.5  ]]
[[40 36]
 [16 54]]
[[ 52  66]
 [ 82 102]]


In [45]:
import numpy 
x=np.array([[5,6],[8,9]])
y=np.array([[8,6],[2,6]])
print(numpy.sqrt(x))
print(numpy.sum(y))
print(numpy.sum(y,axis=0))
print(numpy.sum(y,axis=1))
print(x.T)

[[2.23606798 2.44948974]
 [2.82842712 3.        ]]
22
[10 12]
[14  8]
[[5 8]
 [6 9]]


In [5]:
import numpy as np
A=np.array([[4,7],[2,6]])
A_inv=np.linalg.inv(A)
print("orginal Matrix:in",A)
print("inverse matrix:in",A_inv)

orginal Matrix:in [[4 7]
 [2 6]]
inverse matrix:in [[ 0.6 -0.7]
 [-0.2  0.4]]


In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
print np.sum(arr)
print np.sum(arr,axis=0)
print(n) 

print np.mean(arr)
print np.mean(arr,axis=0)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (2799017582.py, line 3)

In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.sum(arr)

21

In [16]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]]) 
np.sum(arr,axis=0)

array([5, 7, 9])

In [19]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.sum(arr,axis=1)

array([ 6, 15])

In [20]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6,]])
np.sum(arr,axis=1)

array([ 6, 15])

In [22]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6,]])
np.mean(arr)


3.5

In [24]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

In [25]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.mean(arr,axis=1)

array([2., 5.])

In [26]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.max(arr)

6

In [27]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.max(arr,axis=0)

array([4, 5, 6])

In [29]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.max(arr,axis=1)

array([3, 6])

In [30]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.min(arr)

1

In [31]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.min(arr,axis=0)

array([1, 2, 3])

In [32]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
np.min(arr,axis=1)

array([1, 4])

In [34]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
dot=np.dot(a,b)
print(dot)

32


In [37]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
r=np.dot(a,b)
print(r)

[[19 22]
 [43 50]]


In [39]:
import numpy as np
m=np.array([[1,2],[3,4]])
r=np.matmul(m,m)
print(r)

[[ 7 10]
 [15 22]]


In [47]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("orginal:in",a)
print("transposed:in",a.T)

orginal:in [[1 2 3]
 [4 5 6]]
Transposed:in [[1 4]
 [2 5]
 [3 6]]


In [50]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("transposed:in",b.T)

transposed:in [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [88]:
import numpy as np
c=np.array([1,2,3])
print("transposed:in",c.T)
print("orginal shape",c.shape)

transposed:in [1 2 3]
orginal shape (3,)


In [53]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(a)
print("Original array:", a)
print("Cumulative sum:", cumulative_sum)

Original array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]


In [2]:
import pandas as pd

In [89]:
s1= pd.Series([20,30,40,50])
print(s1)

0    20
1    30
2    40
3    50
dtype: int64


In [20]:
s2= pd .Series([10,20,30,40],index=['a','b','c','d'])
print(s2)

a    10
b    20
c    30
d    40
dtype: int64


In [27]:
s3= pd.Series({'a':10,'b':30,'c':50})
print(s3)

a    10
b    30
c    50
dtype: int64


In [29]:
s4= pd.Series(5,index=[0,1,2,3])
print(s4)

0    5
1    5
2    5
3    5
dtype: int64


In [3]:
data={'name':['alice','bob','charlie'],'age':[25,30,35],'salary':[4000,3000,5000]}
df=pd.DataFrame (data)
print(df)

      name  age  salary
0    alice   25    4000
1      bob   30    3000
2  charlie   35    5000


In [21]:
import pandas as pd
df = pd.read_csv('754.csv')
df['total']= df[['german','english','french','arabic']].sum(axis=1)

print(df[['student', 'total']])


  student  total
0    kelu    234
1    menu    255
2   luffy    382
3    zoro    311
4  naruto    253
